/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 8a4682da07c612009fc47d01bb388537)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
